# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: report.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creport.proto\x12\x06report\">\n\x07Officer\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\t\"\x1c\n\nCoordinate\x12\x0e\n\x06values\x18\x01 \x03(\x01\"\xac\x01\n\tSpaceship\x12$\n\talignment\x18\x01 \x01(\x0e\x32\x11.report.Alignment\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1b\n\x04type\x18\x03 \x01(\x0e\x32\r.report.Class\x12\x0e\n\x06length\x18\x04 \x01(\x02\x12\x0c\n\x04size\x18\x05 \x01(\x05\x12\r\n\x05\x61rmed\x18\x06 \x01(\x08\x12!\n\x08officers\x18\x07 \x03(\x0b\x32\x0f.report.Officer* \n\tAlignment\x12\x08\n\x04\x41LLY\x10\x00\x12\t\n\x05\x45NEMY\x10\x01*\\\n\x05\x43lass\x12\x0c\n\x08\x43ORVETTE\x10\x00\x12\x0b\n\x07\x46RIGATE\x10\x01\x12\x0b\n\x07\x43RUISER\x10\x02\x12\r\n\tDESTROYER\x10\x03\x12\x0b\n\x07\x43\x41RRIER\x10\x04\x12\x0f\n\x0b\x44READNOUGHT\x10\x05\x32I\n\x10ReportingService\x12\x35\n\x08GetShips\x12\x12.report.Coordinate\x1a\x11.report.Spaceship\"\x00\x30\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'report_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALIGNMENT']._serialized_start=293
  _globals['_ALIGNMENT']._serialized_end=325
  _globals['_CLASS']._serialized_start=327
  _globals['_CLASS']._serialized_end=419
  _globals['_OFFICER']._serialized_start=24
  _globals['_OFFICER']._serialized_end=86
  _globals['_COORDINATE']._serialized_start=88
  _globals['_COORDINATE']._serialized_end=116
  _globals['_SPACESHIP']._serialized_start=119
  _globals['_SPACESHIP']._serialized_end=291
  _globals['_REPORTINGSERVICE']._serialized_start=421
  _globals['_REPORTINGSERVICE']._serialized_end=494
# @@protoc_insertion_point(module_scope)
