- hosts: all
  become: yes
  tasks:
  - name: Install python3
    ansible.builtin.apt:
      name: python3
      state: latest
  - name: Install nginx
    ansible.builtin.apt:
      name: nginx
      state: latest
  - name: Copy exploit.py
    ansible.builtin.copy:
      src: exploit.py
      dest: /tmp
      mode: '0644'
  - name: Copy consumer.py
    ansible.builtin.copy:
      src: consumer.py
      dest: /tmp
      mode: '0644'
  - name: Run script
    ansible.builtin.command:
      cmd: python3 /tmp/consumer.py -e 4815162342, 3133780085
  - name: Run script for generate data
    ansible.builtin.command:
      cmd: python3 /tmp/producer.py -e 2
